### ISSUE TITLE
[BUG] Vanished players are affecting the player count

### ISSUE THREAD

**Issue by starve-l** [LeftyIsHere/GoldenWaters#5]
**Describe the bug**
vanished players are affecting the player count

**Expected behavior**
when someone is fakeleaving, the playercount should update
**To Reproduce**
1. fakeleave '...'
2. see error '....'
3. 
4. 
evidence: https://imgur.com/a/CYt3BVV
sorry for the bad formatting

**Comment by LeftyIsHere** [comment]
Im not sure there is a way to fix this, but I don't think it really needs changing because usually there are enough players on for the difference in the tab list to not be noticeable. Even if someone does notice, I doubt they would be able to tell where and who the player that is vanished is. I also am unsure if this is even a bug because while they are vanished, they are still on the server. If it does become an issue later on, I will reopen this and attempt to find a way to fix it.

**Comment by kakduman** [comment]
Don't quote me on this but I believe PremiumVanish would be able to hide vanished players on the tablist if you cared enough
